import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<div className=''>
			<Head>
				<title>Instagram Clone</title>
				<meta name='description' content='Instagram Clone generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* Header */}

			{/* Feed Section */}

			{/* Modal */}
		</div>
	);
}
